---
- name: Deploy Spring Boot
  hosts: app
  vars:
    ci_cd:
      namespace: coo-ci-cd
    dev:
      namespace: coo-dev
    test:
      namespace: coo-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
