apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: mongodb-seed
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: mongodb-seed
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
