management:
  server:
    port: 8081
  context-path: /actuator

#mongodb
spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: devapps
      username: mongouser
      password: mongopass
